export * from './Home';
export * from './LogIn';
export * from './SignUp';
export * from './UserInfo';
export * from './OrderHistory';
export * from './WatchedProducts';
// export * from './Search';
// export * from './Settings';
// export * from './User';
// export * from './Login';
// export * from './Register';
